// Auto-generated by scripts/sound/bundle.mjs. Do not edit by hand.
// Source: scripts/sound/{registry,resolver,controller,session,profile-paper-explainer,bundle.template}.mjs

const {
  REGISTRY, SFX_BASE_DIR, getEffect, pickAsset, pickPlaybackRate,
  resolve, resolveAll,
  SoundController, SoundSession,
  paperExplainerProfile,
} = (function () {
// ── registry.mjs ──
// scripts/sound/registry.mjs
// Centralized sound registry for the paper-explainer style.
//
// The animation engine and composition code reference semantic effect names
// (e.g. "write", "drawLoop", "marker"). The registry owns the asset list,
// default volume, loop behavior, variation policy, intensity mapping, and
// concurrent throttle per effect. The rest of the sound system MUST NOT
// touch audio filenames directly — go through the registry.
//
// Per-effect shape:
//   {
//     effect:      string  — semantic key, also the profile mapping target
//     assets:      string[] — file basenames, resolved against SFX_BASE_DIR
//     defaultVolume: number — 0..1, applied to the audio element's .volume
//     loop:        boolean — whether playback is one-shot (false) or
//                            continuous (true). For looped playback during
//                            "during" timing, the session pairs this with
//                            an explicit stop call at clip-end.
//     variation:   { enabled, playbackRateRange: {min,max} } — playback-rate
//                            jitter per spec §12. Range is narrow on purpose.
//     intensity:   "ambient"|"subtle"|"normal"|"emphasis"|"strong"
//                            — default firing intensity (spec §7).
//     timing:      "start"|"during"|"end" — default firing window.
//     maxConcurrent: number — throttle per effect (spec §8).
//   }
//
// Missing assets degrade silently: the resolver returns null and the session
// no-ops the play() call. Animation continues normally (spec §14).

const SFX_BASE_DIR = "templates/audio/sfx";

/** Eight core paper-explainer effects, generated via audioldm-s-full-v2.
 *  Order matches the planned cue list. assets[] length determines variation
 *  selection at play time (random pick per call, seeded by call site — see
 *  session.mjs). */
const REGISTRY = {
  // ─── Writing ───────────────────────────────────────────────────────
  write: {
    effect: "write",
    assets: ["pencil-write-1.wav"],
    defaultVolume: 0.18,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.97, max: 1.03 } },
    intensity: "subtle",
    timing: "during",
    maxConcurrent: 2,
  },
  writeShort: {
    effect: "writeShort",
    assets: ["pencil-write-1.wav"],     // same source, different playback
    defaultVolume: 0.16,
    loop: false,
    variation: { enabled: true, playbackRateRate: 0, playbackRateRange: { min: 0.95, max: 1.05 } },
    intensity: "subtle",
    timing: "start",
    maxConcurrent: 3,
  },
  writeLoop: {
    effect: "writeLoop",
    assets: ["pencil-write-loop-1.wav"],
    defaultVolume: 0.15,
    loop: true,                          // loop for the duration of the write
    variation: { enabled: false, playbackRateRange: { min: 1.0, max: 1.0 } },
    intensity: "subtle",
    timing: "during",
    maxConcurrent: 1,
  },

  // ─── Drawing ───────────────────────────────────────────────────────
  drawStart: {
    effect: "drawStart",
    assets: ["pencil-draw-loop-1.wav"],
    defaultVolume: 0.16,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.97, max: 1.03 } },
    intensity: "subtle",
    timing: "start",
    maxConcurrent: 3,
  },
  drawLoop: {
    effect: "drawLoop",
    assets: ["pencil-draw-loop-1.wav"],
    defaultVolume: 0.14,                 // quieter than write: drawing is
    loop: true,                          // a background texture most of the time
    variation: { enabled: false, playbackRateRange: { min: 1.0, max: 1.0 } },
    intensity: "subtle",
    timing: "during",
    maxConcurrent: 2,
  },
  drawEnd: {
    effect: "drawEnd",
    assets: ["pencil-draw-loop-1.wav"],
    defaultVolume: 0.12,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.95, max: 1.05 } },
    intensity: "subtle",
    timing: "end",
    maxConcurrent: 3,
  },

  // ─── Marker ────────────────────────────────────────────────────────
  marker: {
    effect: "marker",
    assets: ["marker-swipe-1.wav"],
    defaultVolume: 0.22,                 // louder than write: this directs
    loop: false,                          // attention
    variation: { enabled: true, playbackRateRange: { min: 0.96, max: 1.04 } },
    intensity: "normal",
    timing: "during",
    maxConcurrent: 1,
  },
  highlight: {
    effect: "highlight",
    assets: ["marker-swipe-1.wav"],
    defaultVolume: 0.20,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.98, max: 1.02 } },
    intensity: "normal",
    timing: "during",
    maxConcurrent: 1,
  },
  underline: {
    effect: "underline",
    assets: ["marker-swipe-1.wav"],
    defaultVolume: 0.14,                 // quieter than highlight
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.95, max: 1.05 } },
    intensity: "subtle",
    timing: "during",
    maxConcurrent: 1,
  },

  // ─── Placement ─────────────────────────────────────────────────────
  softPop: {
    effect: "softPop",
    assets: ["paper-place-1.wav"],
    defaultVolume: 0.18,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.95, max: 1.05 } },
    intensity: "subtle",
    timing: "start",
    maxConcurrent: 3,
  },
  paperPlace: {
    effect: "paperPlace",
    assets: ["paper-place-1.wav"],
    defaultVolume: 0.20,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.96, max: 1.04 } },
    intensity: "normal",
    timing: "start",
    maxConcurrent: 2,
  },
  cardPlace: {
    effect: "cardPlace",
    assets: ["paper-place-1.wav"],
    defaultVolume: 0.22,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.95, max: 1.05 } },
    intensity: "normal",
    timing: "start",
    maxConcurrent: 2,
  },

  // ─── Movement ──────────────────────────────────────────────────────
  penMove: {
    effect: "penMove",
    assets: ["soft-whoosh-1.wav"],
    defaultVolume: 0.10,                 // ambient; almost inaudible
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.9, max: 1.1 } },
    intensity: "ambient",
    timing: "start",
    maxConcurrent: 1,
  },
  softWhoosh: {
    effect: "softWhoosh",
    assets: ["soft-whoosh-1.wav"],
    defaultVolume: 0.18,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.95, max: 1.05 } },
    intensity: "subtle",
    timing: "start",
    maxConcurrent: 2,
  },

  // ─── Emphasis ──────────────────────────────────────────────────────
  emphasis: {
    effect: "emphasis",
    assets: ["soft-impact-1.wav"],
    defaultVolume: 0.24,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.97, max: 1.03 } },
    intensity: "emphasis",
    timing: "end",
    maxConcurrent: 1,
  },
  impact: {
    effect: "impact",
    assets: ["soft-impact-1.wav"],
    defaultVolume: 0.28,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.96, max: 1.04 } },
    intensity: "emphasis",
    timing: "end",
    maxConcurrent: 1,
  },
  chime: {
    effect: "chime",
    assets: ["chime-bright-1.wav"],
    defaultVolume: 0.22,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.98, max: 1.02 } },
    intensity: "normal",
    timing: "end",
    maxConcurrent: 1,
  },

  // ─── Scene ─────────────────────────────────────────────────────────
  sectionReveal: {
    effect: "sectionReveal",
    assets: ["soft-whoosh-1.wav"],
    defaultVolume: 0.16,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.95, max: 1.05 } },
    intensity: "subtle",
    timing: "start",
    maxConcurrent: 1,
  },
  transition: {
    effect: "transition",
    assets: ["soft-whoosh-1.wav"],
    defaultVolume: 0.20,
    loop: false,
    variation: { enabled: true, playbackRateRange: { min: 0.94, max: 1.06 } },
    intensity: "normal",
    timing: "start",
    maxConcurrent: 1,
  },
};

/** Look up an effect definition. Returns null if the effect is not in the
 *  registry — the resolver treats this as a silent miss, never a throw. */
function getEffect(effectName) {
  return REGISTRY[effectName] ?? null;
}

/** Pick an asset variation deterministically. `seed` is a per-call site
 *  integer (e.g. clipIndex) so the same scene produces the same variation
 *  on every render — no Math.random(), no Date.now() (spec §11). */
function pickAsset(effect, seed = 0) {
  if (!effect || !effect.assets || effect.assets.length === 0) return null;
  const idx = ((seed % effect.assets.length) + effect.assets.length) % effect.assets.length;
  return effect.assets[idx];
}

/** Compute the playback rate for a call, deterministic from `seed`. */
function pickPlaybackRate(effect, seed = 0) {
  if (!effect || !effect.variation?.enabled) return 1.0;
  const { min, max } = effect.variation.playbackRateRange;
  if (min === max) return min;
  // Deterministic LCG-ish lerp on a 0..1 range, then scale.
  const u = ((seed * 2654435761) % 1000) / 1000;
  return min + u * (max - min);
}


// ── controller.mjs ──
// scripts/sound/controller.mjs
// Global SoundController — master mute, master volume, intensity mix,
// and the central asset resolution layer. One controller per composition.
//
// The browser bundle (sound.js) creates the controller and wires its
// `resolveAssetURL(name)` to the actual project-relative path. The engine
// modules (registry, resolver, session) never see URLs.


/** Map an intensity label to a linear volume multiplier (spec §7).
 *  Kept as a small multiplicative mix on top of the per-effect defaultVolume. */
const INTENSITY_MIX = {
  ambient:   0.50,
  subtle:    0.75,
  normal:    1.00,
  emphasis:  1.20,
  strong:    1.40,
};

class SoundController {
  constructor(opts = {}) {
    this.assetBaseURL = opts.assetBaseURL ?? "./.media/sfx/";
    this.assetExtension = opts.assetExtension ?? ".mp3";
    this.masterVolume = opts.masterVolume ?? 1.0;
    this.muted = opts.muted ?? false;
    // List of asset basenames known to be missing on disk — populated
    // lazily as the browser attempts to load them. Playback of a missing
    // asset is silently skipped (spec §14).
    this.missingAssets = new Set();
    this.onMuteChange = opts.onMuteChange || null;
    this.onVolumeChange = opts.onVolumeChange || null;
  }

  mute()       { this.muted = true;  if (this.onMuteChange)   this.onMuteChange(true); }
  unmute()     { this.muted = false; if (this.onMuteChange)   this.onMuteChange(false); }
  setMuted(m)  { m ? this.mute() : this.unmute(); }

  setMasterVolume(v) {
    this.masterVolume = Math.max(0, Math.min(1, Number(v) || 0));
    if (this.onVolumeChange) this.onVolumeChange(this.masterVolume);
  }

  /** Resolve a registry asset basename to a URL the browser can load. */
  resolveAssetURL(basename) {
    return this.assetBaseURL + basename.replace(/\.[^.]+$/, "") + this.assetExtension;
  }

  /** The effective volume for one effect + intensity combination, after
   *  master volume is applied. Returns 0 if muted. */
  effectiveVolume(perEffectVolume, intensity) {
    if (this.muted) return 0;
    const mix = INTENSITY_MIX[intensity] ?? 1.0;
    const raw = (perEffectVolume ?? 0) * mix * this.masterVolume;
    return Math.max(0, Math.min(1, raw));
  }

  /** Expose the registry helpers (so the session can read maxConcurrent
   *  without an extra import). */
  getEffect(name) { return getEffect(name); }
  getRegistry()   { return REGISTRY; }
  getBaseDir()    { return SFX_BASE_DIR; }
}


// ── resolver.mjs ──
// scripts/sound/resolver.mjs
// Animation action → SoundEvent[] resolver.
//
// Precedence (per the spec §6, this is the most important thing this module
// does, so it gets the longest comment):
//
//   explicit sound config  >  action-specific default  >  profile default  >  silence
//
// The author can attach a `sound` field to a clip in one of three forms:
//   1. sound: false                       — disable sound for this clip
//   2. sound: { effect: "marker", ... }   — single SoundEvent (shorthand)
//   3. sound: [ { effect, timing, ... },  — explicit list of SoundEvents
//              { effect, timing, ... } ]
//
// If `sound` is absent, the resolver consults the profile's `actions` map
// keyed by the clip's `action` (e.g. "write", "draw", "highlight"). The
// profile supplies a default SoundEvent[] per action; the resolver expands
// compound actions (e.g. "drawBox" → 1× drawStart + 1× drawLoop + 1× drawEnd
// with a shared group id) per the spec §9 grouping rule.
//
// If the action is not in the profile, the resolver returns [] and the
// session plays nothing. This is the "silence" fallback.
//
// SoundEvent shape (the canonical, serialization-friendly form):
//   {
//     effect:     "drawLoop",
//     timing:     { at: "during" } | { at: "start" } | { at: "end" } |
//                 { at: "absolute", time: 4.2 } | { at: "during", offset: 0.05 },
//     volume?:    number  — override the registry default
//     intensity?: "subtle"|"normal"|"emphasis"|... — override the registry default
//     loop?:      boolean — override the registry default
//     group?:     string  — shared group id for multi-segment grouped sounds
//     fadeIn?:    number  — seconds
//     fadeOut?:   number  — seconds
//   }


/** Expand a shorthand `sound: { effect: "X" }` into a single-event list,
 *  pulling registry defaults for everything the author didn't specify. */
function expandShorthand(s, defaults) {
  if (s === false) return [];
  if (s == null) return null;             // "no explicit config, fall through"
  // Array form
  if (Array.isArray(s)) return s;
  // Object form
  return [{
    effect: s.effect,
    timing: s.timing ?? { at: defaults?.timing ?? "during" },
    volume: s.volume,
    intensity: s.intensity,
    loop: s.loop,
    group: s.group,
    fadeIn: s.fadeIn,
    fadeOut: s.fadeOut,
  }];
}

/** Apply per-effect defaults from the registry to any SoundEvent that
 *  doesn't override them. Returns a new array — does not mutate input. */
function applyRegistryDefaults(events) {
  return events
    .map((e) => {
      const def = getEffect(e.effect);
      if (!def) return null;             // unknown effect → drop
      return {
        ...e,
        volume:   e.volume   ?? def.defaultVolume,
        intensity:e.intensity ?? def.intensity,
        loop:     e.loop     ?? def.loop,
      };
    })
    .filter(Boolean);
}

/** Group-aware expansion: a single logical "draw" action becomes three
 *  events sharing a group id, so the session can coalesce them. */
function expandGroupedAction(action, baseEvent) {
  if (action === "drawBox" || action === "drawCard") {
    return [
      { ...baseEvent, effect: "drawStart", timing: { at: "start" }, group: `${baseEvent.group ?? action}` },
      { ...baseEvent, effect: "drawLoop",  timing: { at: "during" }, loop: true, group: `${baseEvent.group ?? action}` },
      { ...baseEvent, effect: "drawEnd",   timing: { at: "end" }, group: `${baseEvent.group ?? action}` },
    ];
  }
  if (action === "drawCircle") {
    return [
      { ...baseEvent, effect: "drawStart", timing: { at: "start" }, group: `${baseEvent.group ?? action}` },
      { ...baseEvent, effect: "drawLoop",  timing: { at: "during" }, loop: true, group: `${baseEvent.group ?? action}` },
      { ...baseEvent, effect: "drawEnd",   timing: { at: "end" }, group: `${baseEvent.group ?? action}` },
      { ...baseEvent, effect: "emphasis",  timing: { at: "end", offset: 0.05 } },
    ];
  }
  if (action === "draw") {
    return [
      { ...baseEvent, effect: "drawStart", timing: { at: "start" } },
      { ...baseEvent, effect: "drawLoop",  timing: { at: "during" }, loop: true },
      { ...baseEvent, effect: "drawEnd",   timing: { at: "end" } },
    ];
  }
  if (action === "write") {
    return [
      { ...baseEvent, effect: "writeShort", timing: { at: "start" } },
      { ...baseEvent, effect: "writeLoop",  timing: { at: "during" }, loop: true },
    ];
  }
  if (action === "highlight") {
    return [
      { ...baseEvent, effect: "marker", timing: { at: "during" } },
    ];
  }
  if (action === "underline") {
    return [
      { ...baseEvent, effect: "underline", timing: { at: "during" } },
    ];
  }
  if (action === "appear") {
    return [
      { ...baseEvent, effect: "softPop", timing: { at: "start" } },
    ];
  }
  if (action === "place" || action === "cardReveal") {
    return [
      { ...baseEvent, effect: "cardPlace", timing: { at: "start" } },
    ];
  }
  if (action === "sectionReveal") {
    return [
      { ...baseEvent, effect: "sectionReveal", timing: { at: "start" } },
    ];
  }
  if (action === "importantReveal") {
    return [
      { ...baseEvent, effect: "impact", timing: { at: "end" } },
    ];
  }
  if (action === "transition") {
    return [
      { ...baseEvent, effect: "transition", timing: { at: "start" } },
    ];
  }
  // Unknown action — single-effect default pass-through, caller decides.
  return [baseEvent];
}

/** Resolve the SoundEvent[] for one clip.
 *
 *  @param clip  { action?: string, sound?: false|SoundEvent|SoundEvent[] }
 *  @param profile  { actions: Record<string, SoundEvent|SoundEvent[]> }
 *  @returns SoundEvent[]  — possibly empty; never null
 */
function resolve(clip, profile) {
  // 1) explicit `sound: false` short-circuits everything.
  if (clip && clip.sound === false) return [];

  // 2) explicit sound config (shorthand or array) wins over the profile.
  const explicit = clip ? expandShorthand(clip.sound, null) : null;
  if (explicit !== null) {
    return applyRegistryDefaults(explicit);
  }

  // 3) profile-driven default for this action.
  const action = clip?.action;
  if (!action || !profile?.actions) return [];
  const profileDefault = profile.actions[action];
  if (profileDefault == null) return [];

  const expanded = expandGroupedAction(action, { ...profileDefault });
  return applyRegistryDefaults(expanded);
}

/** Resolve every clip in a list. Returns a list of `{ clip, events }`
 *  pairs, preserving order. Clips with no resolved events are still
 *  included (events: []) so the caller can iterate uniformly. */
function resolveAll(clips, profile) {
  return clips.map((clip) => ({ clip, events: resolve(clip, profile) }));
}


// ── session.mjs ──
// scripts/sound/session.mjs
// SoundSession — owns the lifecycle of all currently-playing SFX on one
// timeline. This is where the spec's §11 hard requirements live:
//
//   1. Loops start exactly with the animation
//   2. Loops continue only while the visual action is active
//   3. Loops stop or fade when the animation completes
//   4. Loops stop immediately if the animation is cancelled
//   5. Loops stop when the scene changes
//   6. Loops stop when playback restarts
//   7. Loops never survive component unmounting
//
// The session exposes a small imperative API the timeline can call:
//   session.play(event, { clipStart, clipDuration, seed }) → handle
//   session.stop(handle)
//   session.stopGroup(groupId)
//   session.stopAll()
//
// Handles are tiny: { stop: () => void, effect: string, group?: string }.
// The timeline stores handles returned from `play()` so it can stop them
// in teardown or on restart.
//
// This module is pure ESM and DOM-free — the actual `<audio>` element
// creation lives in sound.js (the browser bundle). The session just
// tracks an array of handle-shaped objects and calls their stop().

const NOOP = () => {};
const NOOP_HANDLE = Object.freeze({ stop: NOOP, effect: null });

class SoundSession {
  constructor({ controller, onPlay } = {}) {
    this.controller = controller;        // may be null in tests
    this.onPlay = onPlay || null;        // browser-only: (event, handle) => void
    this.handles = [];                   // active handles
    this.counts = new Map();             // effect → active count (for throttle)
  }

  /** Start a sound for one event at a specific timeline position.
   *  Returns a handle. The handle's stop() is idempotent. */
  play(event, ctx = {}) {
    const { effect, timing, group, loop, volume, intensity, fadeIn, fadeOut } = event;
    if (!effect) return NOOP_HANDLE;

    // Throttle per spec §8 — if maxConcurrent exceeded, drop the lowest-intensity
    // event. (We just drop this one if the effect is already at max.)
    const def = this.controller?.getEffect?.(effect);
    const max = def?.maxConcurrent ?? Infinity;
    const cur = this.counts.get(effect) ?? 0;
    if (cur >= max) {
      // console.warn would be the spec's behavior; we just no-op.
      return NOOP_HANDLE;
    }
    this.counts.set(effect, cur + 1);

    // Build the handle up-front so stop() works even if onPlay is sync/async.
    const handle = {
      effect,
      group: group ?? null,
      _stopped: false,
      stop: () => {
        if (handle._stopped) return;
        handle._stopped = true;
        const c = this.counts.get(effect) ?? 0;
        this.counts.set(effect, Math.max(0, c - 1));
        const i = this.handles.indexOf(handle);
        if (i >= 0) this.handles.splice(i, 1);
        if (handle._realStop) handle._realStop();
      },
    };
    this.handles.push(handle);

    // Hand off to the browser-side player (no-op in tests).
    if (this.onPlay) {
      try {
        const real = this.onPlay({ event, ctx, handle });
        if (real && typeof real.stop === "function") handle._realStop = real.stop;
      } catch {
        // Spec §14: audio failure never breaks the visual timeline.
      }
    }
    return handle;
  }

  stop(handle) {
    if (handle && typeof handle.stop === "function") handle.stop();
  }

  /** Stop every active handle in a group. Used by drawBox/drawCard expansion. */
  stopGroup(groupId) {
    if (!groupId) return;
    // Snapshot — stop() mutates this.handles.
    const matches = this.handles.filter((h) => h.group === groupId);
    for (const h of matches) h.stop();
  }

  /** Stop every active handle. Called on scene change, restart, unmount. */
  stopAll() {
    // Snapshot — stop() mutates this.handles.
    const all = this.handles.slice();
    for (const h of all) h.stop();
  }

  /** Number of currently-active handles. Exposed for tests + debug. */
  size() {
    return this.handles.length;
  }
}


// ── profile-paper-explainer.mjs ──
// scripts/sound/profile-paper-explainer.mjs
// The paper-explainer sound profile. Maps animation actions to default
// SoundEvent templates — the per-effect registry fields (volume, loop,
// intensity, timing) are applied by the resolver.
//
// The author can still override any of this with an explicit `sound:`
// field on the clip (per the spec §6 precedence).

const paperExplainerProfile = {
  style: "paper-explainer",
  description: "Hand-drawn notebook explainer. Warm paper, pencil + marker, restrained emphasis.",

  // Default timing per action: when the sound fires within a clip. The
  // resolver's expandGroupedAction overrides these for compound actions.
  actions: {
    // Writing
    write:           { effect: "write" },         // resolver expands to writeShort+writeLoop
    writeShort:      { effect: "writeShort" },
    writeLoop:       { effect: "writeLoop" },

    // Drawing
    draw:            { effect: "drawLoop" },      // resolver expands to start/loop/end
    drawLine:        { effect: "drawLoop" },
    drawArrow:       { effect: "drawLoop" },
    drawBox:         { effect: "drawLoop" },      // resolver adds grouping
    drawCard:        { effect: "drawLoop" },      // resolver adds grouping
    drawCircle:      { effect: "drawLoop" },      // resolver adds emphasis at end
    drawStart:       { effect: "drawStart" },
    drawEnd:         { effect: "drawEnd" },

    // Marker
    highlight:       { effect: "marker" },
    underline:       { effect: "underline" },
    marker:          { effect: "marker" },

    // Placement
    appear:          { effect: "softPop" },
    place:           { effect: "cardPlace" },
    cardReveal:      { effect: "cardPlace" },
    softPop:         { effect: "softPop" },
    paperPlace:      { effect: "paperPlace" },
    cardPlace:       { effect: "cardPlace" },

    // Movement
    penMove:         { effect: "penMove" },
    softWhoosh:      { effect: "softWhoosh" },

    // Emphasis
    emphasis:        { effect: "emphasis" },
    impact:          { effect: "impact" },
    chime:           { effect: "chime" },
    importantReveal: { effect: "impact" },

    // Scene
    sectionReveal:   { effect: "sectionReveal" },
    transition:      { effect: "transition" },
  },
};

  return {
    REGISTRY, SFX_BASE_DIR, getEffect, pickAsset, pickPlaybackRate,
    resolve, resolveAll,
    SoundController, SoundSession,
    paperExplainerProfile,
  };
})();

// scripts/sound/bundle.template.mjs
// Browser-side entry point for the sound system. This file is the template
// the build copies into each project as `sound.js` — it is the bridge
// between the engine modules (DOM-free) and the live DOM/audio.
//
// Responsibilities (in order of importance):
//   1. Create a SoundController bound to the project-relative asset URL.
//   2. Create a SoundSession that wraps the browser's <audio> playback.
//   3. Walk the composition root (#root) for elements with `data-sound`.
//   4. For each data-sound, schedule tl.call() entries on the existing
//      GSAP timeline. The timeline is the source of truth for timing
//      (spec §10), not setTimeout / setInterval.
//   5. Expose `window.__sound` for Studio editing / mute toggle.
//   6. Stop everything on timeline restart, scene change, and unmount
//      (spec §11 hard requirements 5–7).
//
// `data-sound` attribute format (parse on element-read):
//   data-sound="action:write"
//   data-sound="action:draw,group:drawBox-1,seed:2"
//   data-sound="action:highlight,intensity:emphasis"
//   data-sound="action:none"   (silence)
//
// For authoring convenience, the build script can also emit fully-expanded
// JSON via data-sound-events="[ {...}, {...} ]" — this bypasses the
// resolver and lets the author hand-curate an event list.
//
// Audio playback strategy:
//   - For loop=false effects, the runtime creates an <audio> element, sets
//     volume from controller.effectiveVolume(), calls .play(), and lets it
//     play to completion. If autoplay is rejected, we don't retry (spec
//     §14: audio failure never breaks the visual timeline).
//   - For loop=true effects, the runtime creates an <audio loop> and stops
//     it via the session when the timeline reaches the clip end (or
//     sooner on cancel).
//   - The same <audio> element is reused per effect across calls (a small
//     pool), so we don't spawn hundreds of elements.



const root = document.getElementById("root");
const compositionId = root?.getAttribute("data-composition-id");

function tryBoot() {
  if (!root) {
    console.warn("[sound] no #root; sound system disabled");
    return;
  }
  if (typeof gsap === "undefined") {
    console.warn("[sound] no GSAP on window; sound system disabled");
    return;
  }
  const timeline = (window.__timelines && window.__timelines[compositionId]) ||
                   (window.__timelines && Object.values(window.__timelines)[0]);
  if (!timeline) {
    // Timeline isn't registered yet — the composition script may run
    // after this one. Poll for up to ~1s, then give up.
    if (tryBoot._tries == null) tryBoot._tries = 0;
    tryBoot._tries += 1;
    if (tryBoot._tries < 60) {
      requestAnimationFrame(tryBoot);
    } else {
      console.warn("[sound] no timeline registered on window.__timelines within 1s; sound system disabled");
    }
    return;
  }
  boot(root, timeline);
}

tryBoot();

function boot(root, timeline) {
  const controller = new SoundController({
    assetBaseURL: "./.media/sfx/",
    assetExtension: ".mp3",
  });
  const session = new SoundSession({ controller, onPlay: playOne });

  // Element pool: one <audio> per effect, reused. Keeps DOM small and
  // browser autoplay policies happy (one user gesture can unlock them all).
  const pool = new Map();
  function getOrCreate(effect) {
    let a = pool.get(effect);
    if (a) return a;
    const def = getEffect(effect);
    if (!def) return null;
    const url = controller.resolveAssetURL(def.assets[0]);
    a = new Audio(url);
    a.preload = "auto";
    a.loop = !!def.loop;
    a.addEventListener("error", () => controller.missingAssets.add(def.assets[0]));
    pool.set(effect, a);
    return a;
  }

  // The actual play() callback passed to the session. The session wraps
  // this in try/catch (spec §14) so we don't need to.
  function playOne({ event, ctx, handle }) {
    const def = getEffect(event.effect);
    if (!def) return null;
    const url = controller.resolveAssetURL(def.assets[0]);
    const vol = controller.effectiveVolume(event.volume, event.intensity);
    if (vol <= 0) return null;

    // For loop=false: create a fresh Audio each call. Cheap, and it
    // guarantees no overlap of the same one-shot.
    if (!event.loop && !def.loop) {
      const a = new Audio(url);
      a.volume = vol;
      a.playbackRate = pickPlaybackRate(def, ctx.seed ?? 0);
      a.preload = "auto";
      a.play().catch(() => { /* autoplay blocked — silent miss */ });
      return { stop: () => { try { a.pause(); a.currentTime = 0; } catch {} } };
    }
    // For loop=true: use the pooled element; bind the session to it.
    const a = getOrCreate(event.effect);
    if (!a) return null;
    a.volume = vol;
    a.currentTime = 0;
    a.play().catch(() => {});
    return { stop: () => { try { a.pause(); a.currentTime = 0; } catch {} } };
  }

  // Walk the root for elements with data-sound. For each clip, resolve
  // its SoundEvent[] via the profile-driven resolver, then schedule
  // tl.call() for each event.
  const clips = Array.from(root.querySelectorAll("[data-sound]"));
  for (const el of clips) {
    const start = parseFloat(el.getAttribute("data-start") ?? "0") || 0;
    const duration = parseFloat(el.getAttribute("data-duration") ?? "0") || 0;
    const action = el.getAttribute("data-action") || undefined;
    const explicit = el.getAttribute("data-sound-events");
    const seed = parseInt(el.getAttribute("data-sound-seed") ?? "0", 10) || 0;

    let events;
    if (explicit) {
      // Hand-authored event list (authored in the build step)
      try { events = JSON.parse(explicit); }
      catch { events = []; }
    } else {
      events = resolve({ action, sound: false }, paperExplainerProfile);
      // sound: false above ensures we ONLY get the profile-driven defaults;
      // if the user wanted to override, they would have used data-sound-events.
    }

    if (!events || events.length === 0) continue;

    for (const ev of events) {
      const at = ev.timing?.at ?? def(ev).timing ?? "during";
      const offset = ev.timing?.offset ?? 0;
      const absTime = (at === "start") ? start
                    : (at === "end")   ? (start + duration)
                    : (at === "absolute") ? (ev.timing.time ?? 0)
                    :  start;            // "during" — fire at start, loop runs till end
      const when = absTime + offset;
      timeline.call(() => {
        const h = session.play(ev, { clipStart: start, clipDuration: duration, seed });
        if (at === "during" && ev.loop !== false) {
          // For looped during-effects, schedule a stop at clip end.
          const stopAt = start + duration;
          if (stopAt > when) {
            timeline.call(() => h.stop(), [], stopAt);
          }
        }
      }, [], when);
    }
  }

  // Alternative: a hand-authored schedule on window.__soundSchedule.
  // The composition's existing timeline script can push entries to
  // this array before sound.js boots (or even after — the array is
  // read once at boot time, then the timeline calls are made).
  //   window.__soundSchedule = [
  //     { start: 2.0, duration: 8.0, action: "write", seed: 0 },
  //     { start: 10.0, duration: 11.0, action: "cardReveal", seed: 1 },
  //     ...
  //   ];
  if (Array.isArray(window.__soundSchedule)) {
    for (const row of window.__soundSchedule) {
      const { start, duration, action, seed } = row;
      const events = resolve({ action }, paperExplainerProfile);
      if (!events || events.length === 0) continue;
      for (const ev of events) {
        const at = ev.timing?.at ?? def(ev).timing ?? "during";
        const offset = ev.timing?.offset ?? 0;
        const absTime = (at === "start") ? start
                      : (at === "end")   ? (start + duration)
                      : (at === "absolute") ? (ev.timing.time ?? 0)
                      :  start;
        const when = absTime + offset;
        timeline.call(() => {
          const h = session.play(ev, { clipStart: start, clipDuration: duration, seed: seed ?? 0 });
          if (at === "during" && ev.loop !== false) {
            const stopAt = start + duration;
            if (stopAt > when) {
              timeline.call(() => h.stop(), [], stopAt);
            }
          }
        }, [], when);
      }
    }
  }

  // Spec §11 hard requirements 5–7: scene change, restart, unmount.
  // GSAP doesn't fire a "restart" event we can listen to, but the
  // timeline's onComplete fires at end-of-playback — at which point the
  // session is already empty (each handle stopped itself via tl.call).
  // The remaining case is "user clicks replay": that's just tl.restart()
  // from outside, and we expose a stopAll() helper for that.
  window.__sound = {
    controller,
    session,
    mute:        () => controller.mute(),
    unmute:      () => controller.unmute(),
    setMuted:    (m) => controller.setMuted(m),
    setVolume:   (v) => controller.setMasterVolume(v),
    stopAll:     () => session.stopAll(),
    size:        () => session.size(),
  };
}

// Small helper used above. The `def(ev)` call sites need the registry
// default timing if the event doesn't carry one. Kept inline so we don't
// need a separate import.
function def(ev) {
  const d = getEffect(ev.effect);
  return d || { timing: "during" };
}

