// projects/emergency-fund-sizing/04-video/timing.mjs
// Per-project copy of scripts/sound/timing.mjs. Generated by
// scripts/build-video.mjs. The REVEAL constants below are FIRST-PASS
// PLACEHOLDERS — re-measure with faster-whisper after the first VO
// regen and update the per-concept C1_REVEAL..C5_REVEAL constants to
// match the actual MP3, then re-run ./regen.sh to cascade the new
// values into index.html.
//
// 5 concepts (not 6) — the v1 default schedule assumed 6 sections;
// this file is the per-project variant for emergency-fund-sizing.

// scripts/sound/timing.mjs
// Single source of truth for the video's reveal schedule.
//
// Every other consumer (the composition's inline <script> in
// index.html, scripts/sound/emit-static-sfx.mjs that generates the
// declarative SFX <audio> block) reads from here. Changing a value
// in this file and re-running the build step (node scripts/sound/
// inject-static-sfx.mjs <path/to/index.html>) updates the entire
// cascade — flash pre-roll, voiceover start, all SFX cues, every
// section reveal.
//
// Constants and the schedule are derived from the voiceover, not
// arbitrary padding. The VO is split into 7 sections: intro, 5
// concepts, outro. Each section's REVEAL duration is sized to fit
// that section's spoken content.

// ── Tunable constants (the only knobs in the system) ─────────────
export const FLASH_DURATION       = 1.0;   // pre-roll: finished page shown for this many seconds before reveal
export const FLASH_FADE           = 0.2;   // pre-roll fade-out duration at the end of FLASH_DURATION
export const VO_DURATION          = 254.1; // voiceover.mp3 length — must match the actual MP3 (measured by faster-whisper)
// NOTE: VO_DURATION above is the FIRST-PASS number from the first
// regen. If the script is trimmed/expanded, re-measure and update.

// Per-section reveal durations, measured from the Paul/VibeVoice VO
// via faster-whisper (per the audio-visual-sync rule in MEMORY.md).
// The script has 7 sections (header + 5 concepts + footer) and the
// durations below are placeholders. Change the script and re-measure;
// the cascade below will re-emit the matching schedule.
export const HEADER_REVEAL        = 19.7;   // intro ("Five things to know about your emergency fund…")
export const C1_REVEAL            = 31.9;  // c1  ("Why the 3–6 month rule is wrong…")
export const C2_REVEAL            = 26.4;  // c2  ("The formula: essentials, not income…")
export const C3_REVEAL            = 33.8;  // c3  ("Pick your months by job type…")
export const C4_REVEAL            = 34.3;  // c4  ("Where to park it…")
export const C5_REVEAL            = 24.3;  // c5  ("How to build it…")
export const OUTRO_REVEAL         = 83.7;  // outro ("That's your emergency fund…")

// Backwards-compat: the original schedule used a single CONCEPT_REVEAL
// for all concepts. We now allow per-concept overrides, so define it
// as a fallback for the (unlikely) path that reads the old name.
export const CONCEPT_REVEAL = C1_REVEAL;

// Derived (do not edit by hand)
export const TOTAL_REVEAL  = HEADER_REVEAL + C1_REVEAL + C2_REVEAL + C3_REVEAL + C4_REVEAL + C5_REVEAL + OUTRO_REVEAL;
export const COMPOSITION_DURATION = FLASH_DURATION + TOTAL_REVEAL;

// ── Schedule (7 reveal groups) ────────────────────────────────────
export const schedule = [
  { key: 'header', start: 0,                                       dur: HEADER_REVEAL  },
  { key: 'c1',     start: HEADER_REVEAL,                           dur: C1_REVEAL      },
  { key: 'c2',     start: HEADER_REVEAL + C1_REVEAL,               dur: C2_REVEAL      },
  { key: 'c3',     start: HEADER_REVEAL + C1_REVEAL + C2_REVEAL,   dur: C3_REVEAL      },
  { key: 'c4',     start: HEADER_REVEAL + C1_REVEAL + C2_REVEAL + C3_REVEAL,                  dur: C4_REVEAL      },
  { key: 'c5',     start: HEADER_REVEAL + C1_REVEAL + C2_REVEAL + C3_REVEAL + C4_REVEAL,       dur: C5_REVEAL      },
  { key: 'footer', start: HEADER_REVEAL + C1_REVEAL + C2_REVEAL + C3_REVEAL + C4_REVEAL + C5_REVEAL, dur: OUTRO_REVEAL   },
].map(row => ({ ...row, start: row.start + FLASH_DURATION }));

// ── What the inject step patches in the inline <script> ──────────
export const INLINE_PATCH_FIELDS = [
  'FLASH_DURATION', 'FLASH_FADE', 'VO_DURATION',
  'HEADER_REVEAL', 'C1_REVEAL', 'C2_REVEAL', 'C3_REVEAL', 'C4_REVEAL', 'C5_REVEAL', 'OUTRO_REVEAL',
];

// ── What the inject step patches in the static HTML markup ────────
export const FLASH_TOTAL = FLASH_DURATION + FLASH_FADE;  // total time the flash is on screen
export const MARKUP_PATCH_RULES = [
  { anchor: 'id="flash-preview"', attr: 'data-duration', value: FLASH_TOTAL },
  { anchor: 'id="vo"', attr: 'data-start', value: FLASH_DURATION },
  { anchor: 'id="vo"', attr: 'data-duration', value: VO_DURATION },
  { anchor: '<body class="clip"', attr: 'data-duration', value: COMPOSITION_DURATION },
  { anchor: 'id="root"', attr: 'data-duration', value: COMPOSITION_DURATION },
  { anchor: 'id="page-bg"', attr: 'data-duration', value: COMPOSITION_DURATION },
];
